# Generated by Django 5.1.6 on 2025-04-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_city_member_email_member_phone_member_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Membarsa'},
        ),
    ]
