# Generated by Django 5.1.6 on 2025-04-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_options_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Membarsa'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
